server:
  port : 8501

spring:
  application:
    name: MySqlJpaIntegration
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?createDatabaseIfNotExist=true
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: mysql-jpa-integration
      max-lifetime: 2000000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
